#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/tlecailtel/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/tlecailtel/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/tlecailtel/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/tlecailtel/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# Autologout on consoles
if [[ "$(tty)" =~ /dev/tty[0-9] ]]; then export TMOUT=900;fi


# Activate kubectl auto-completion for zsh
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)


# Configure cd on quit for nnn when ^g is pressed
n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo 'nnn is already running'
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    # export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

export NNN_PLUG='p:preview-tui'
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_OPENER='bat'

# Use nnn with the following options:
# * use NNN_OPENER, and assume it has only CLI utilities
# * copy selected filepaths to clipboard & show notis on cp/mv/rm,
# * show hidden files
alias n='n -cxH'


# Show hidden files in zsh completion
compinit
_comp_options+=(globdots)


# Add kubectl context & namespace to prompt
autoload -U colors; colors
source ~/kubectl.zsh


# Make diff look like git diff
alias diff='colordiff -u'


# Confirmation prompt
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'


# Reverse mv
mvr () {
    mv $2 $1
}


# Create a directory and cd into it
mcd() {
    mkdir "${1}" && cd "${1}"
}


# Go up [n] directories
up() {
    local cdir="$(pwd)"
    if [[ "${1}" == "" ]]; then
        cdir="$(dirname "${cdir}")"
    elif ! [[ "${1}" =~ ^[0-9]+$ ]]; then
        echo "Error: argument must be a number"
    elif ! [[ "${1}" -gt "0" ]]; then
        echo "Error: argument must be positive"
    else
        for ((i=0; i<${1}; i++)); do
            local ncdir="$(dirname "${cdir}")"
            if [[ "${cdir}" == "${ncdir}" ]]; then
                break
            else
                cdir="${ncdir}"
            fi
        done
    fi
    cd "${cdir}"
}


alias my_ip='curl ifconfig.me'


set_proxy () {
    export http_proxy=http://your_proxy;
    export https_proxy=$http_proxy;
    echo "http_proxy and https_proxy set to: $http_proxy"
}


unset_proxy () {
    unset http_proxy;
    unset https_proxy;
    echo 'http_proxy and https_proxy successfully unset'
}
