#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Disable Python venv prompt (I already use the one from Prezto)
export VIRTUAL_ENV_DISABLE_PROMPT=1


# Press capital Q to "cd on quit" ranger
function ranger {
    local IFS=$'\t\n'
    local tempfile="$(mktemp -t tmp.XXXXXX)"
    local ranger_cmd=(
        command
        ranger
        --cmd="map Q chain shell echo %d > "$tempfile"; quitall"
    )

    ${ranger_cmd[@]} "$@"
    if [[ -f "$tempfile" ]] && [[ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]]; then
        cd -- "$(cat "$tempfile")" || return
    fi
    command rm -f -- "$tempfile" 2>/dev/null
}
alias n=ranger


# Autologout on consoles
if [[ "$(tty)" =~ /dev/tty[0-9] ]]; then export TMOUT=900;fi


# Activate kubectl auto-completion for zsh
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)


# Don't suggest command corrections
unsetopt CORRECT


# Show hidden files in zsh completion
compinit
_comp_options+=(globdots)


# Enable zoxide (cd alternative)
eval "$(zoxide init zsh)"


# Add kubectl context & namespace to prompt
autoload -U colors; colors
source ~/kubectl.zsh


# Confirmation prompt
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'


# Reverse mv
mvr () {
    mv $2 $1
}


# Create a directory and cd into it
mkcd() {
    mkdir "${1}" && cd "${1}"
}


alias c='clear'
alias my_ip='curl ifconfig.me'


set_proxy () {
    export http_proxy=http://your_proxy;
    export https_proxy=$http_proxy;
    echo "http_proxy and https_proxy set to: $http_proxy"
}


unset_proxy () {
    unset http_proxy;
    unset https_proxy;
    echo 'http_proxy and https_proxy successfully unset'
}
