#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# custom aliases
alias myip="curl ifconfig.me; echo"
alias fd=fdfind
alias rg="nocorrect rg"

# custom functions
mkcd () {
    mkdir -p "$1"; cd "$1"
}

update_dns () {
    sudo sed -i  -E 's/(^nameserver 192)/# \1/g' /etc/resolv.conf
}

set_proxy () {
    export http_proxy=your_proxy;
    export https_proxy=$http_proxy;
}

unset_proxy () {
    unset http_proxy;
    unset https_proxy;
}
